homeassistant:
  name: Home
  unit_system: imperial
  time_zone: America/Los_Angeles
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  customize: !include_dir_merge_named customization

recorder:
  purge_days: 14

## Features ##
# Enables the frontend
frontend:
# Checks for available updates
#updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# Track the sun
sun:
# Enables Amazon Echo / Hue functions:
emulated_hue:
  expose_by_default: false
  
alexa: !include alexa.yaml
## Groups ##
group: !include groups.yaml
## HTTP ##
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
# Sensor
sensor: !include sensor.yaml

## Scripts ##
script: !include_dir_merge_list scripts
## Scenes ##
scene: !include_dir_merge_list scenes
## Automation ##
automation: !include_dir_merge_list automation
## Inputs ##
input_boolean: !include input_boolean.yaml
input_slider: !include input_slider.yaml
input_select: !include input_select.yaml
binary_sensor: !include binary_sensors.yaml

## Cover ##
cover: !include cover.yaml

## Panels ##
panel_custom: !include panel_custom.yaml

## Configurations ##
config:

zwave:
  usb_path: /dev/zwave
  config_path: /srv/homeassistant/src/open-zwave-control-panel/config
  autoheal: false
  polling_interval: 60000
  
# zha:
  # usb_path: /dev/ttyUSB0
  # database_path: /home/homeassistant/.homeassistant/zigbee.db

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet


# Text to speech
tts:
  platform: google

device_tracker:
  - platform: owntracks
  - platform: bluetooth_tracker
    device_id: hci0

mqtt:
  broker: m13.cloudmqtt.com
  port: 14579
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 100
  icon: mdi:home

zone 2:
  name: Tyler's Work
  latitude: !secret tylers_work_latitude
  longitude: !secret tylers_work_longitude
  radius: 250
  icon: mdi:worker

zone 3:
  name: Elementry School
  latitude: !secret saywer_school_latitude
  longitude: !secret saywer_school_longitude
  radius: 250
  icon: mdi:school

logger:
  default: warning
  logs:
    homeassistant.components.device_tracker.mqtt: debug

light:
  platform: osramlightify
  host: 192.168.1.130
  scan_interval: 5

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ifttt:
  key: !secret ifttt

media_player:
  - platform: sonos
